name: Private Action
description: Runs a Private Action

inputs:
  target-token:
    description: 'Personal Access Token with repo scope for targeted private action'
    required: false
  target-action:
    description: 'Private Action {owner}/{repo}[/{path}][@{ref}]'
    required: true

  # Optional args from other actions to hide warnings
  npm-token:
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
